# Generated by Django 4.2.11 on 2026-05-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel & Procurement'), ('UTILITY_ELEC', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('ingested_by', models.CharField(max_length=200)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='raw_uploads/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('processing_log', models.JSONField(default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestions', to='core.tenant')),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('parse_status', models.CharField(choices=[('OK', 'Parsed OK'), ('WARNING', 'Parsed with warnings'), ('ERROR', 'Parse error — no normalized record produced')], default='OK', max_length=10)),
                ('parse_errors', models.JSONField(default=list)),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.dataingestion')),
            ],
            options={
                'ordering': ['ingestion', 'row_number'],
                'unique_together': {('ingestion', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('stationary_combustion', 'Stationary Combustion'), ('mobile_combustion', 'Mobile Combustion'), ('purchased_electricity', 'Purchased Electricity'), ('business_travel_air', 'Business Travel — Air'), ('business_travel_hotel', 'Business Travel — Hotel'), ('business_travel_ground', 'Business Travel — Ground'), ('purchased_goods', 'Purchased Goods & Services')], max_length=50)),
                ('facility_id', models.CharField(blank=True, max_length=100)),
                ('facility_name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('activity_quantity_raw', models.DecimalField(decimal_places=4, max_digits=18)),
                ('activity_unit_raw', models.CharField(max_length=30)),
                ('activity_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('activity_unit', models.CharField(max_length=20)),
                ('emission_factor_value', models.DecimalField(decimal_places=6, max_digits=12)),
                ('emission_factor_unit', models.CharField(max_length=50)),
                ('emission_factor_source', models.CharField(max_length=200)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=200)),
                ('flags', models.JSONField(default=list)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.tenant')),
            ],
            options={
                'ordering': ['-period_start', 'scope'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('activity_unit', models.CharField(max_length=20)),
                ('kg_co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(max_length=200)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', '-valid_from'],
                'indexes': [models.Index(fields=['category', 'valid_from'], name='ingestion_e_categor_8dbac1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INGESTION_STARTED', 'Ingestion started'), ('INGESTION_COMPLETE', 'Ingestion complete'), ('INGESTION_FAILED', 'Ingestion failed'), ('RECORD_CREATED', 'Record created'), ('RECORD_REVIEWED', 'Record reviewed'), ('RECORD_FLAGGED', 'Record flagged'), ('RECORD_LOCKED', 'Record locked'), ('RECORD_EDITED', 'Record edited'), ('BULK_REVIEW', 'Bulk review')], max_length=30)),
                ('actor', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('ingestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='ingestion.dataingestion')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='ingestion.normalizedrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'review_status'], name='ingestion_n_tenant__3e9974_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'scope'], name='ingestion_n_tenant__14f5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['period_start', 'period_end'], name='ingestion_n_period__b96e53_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'is_suspicious'], name='ingestion_n_tenant__b056f9_idx'),
        ),
    ]
